"""Write the real paper entry and reviewer-only workflow descriptions."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];DOCS=ROOT/'docs';BASE='data/gleason-2024-cu-oxidation';ASSET='assets/gleason-2024-cu-oxidation';PAPER='https://www.nature.com/articles/s41524-024-01408-1';CODE='https://github.com/smglsn12/ML_XAS_EELS/tree/85e0f34e448247f6c7a01705807dae39dd1d6cbd'

def file(q,name,description):return {'name':name,'url':f'{BASE}/inputs/{q}/{name}','description':description}
def figure(name,label,caption):return {'image':f'{ASSET}/{name}','label':label,'caption':caption,'url':PAPER}

def make(q,title,inputs,background,instruction,reason,check,steps,evidence,figures=None,thresholds=None):
    truth=[{'name':'expected.json','url':f'{BASE}/verification/{q}/expected.json','description':'Evaluator-only numerical targets; see provenance.json for their evidence type.'}]
    for name in evidence:truth.append({'name':name,'url':f'{BASE}/verification/{q}/{name}','description':'Evaluator-only numerical comparison policy.' if name.endswith('.json') else 'Evaluator-only numerical comparison table.'})
    methods=[{'name':q+'_candidate_workflow.json','url':f'{BASE}/workflows/{q}.json','description':'Worked candidate tool sequence, actual execution record, and limitations. Exclude from agent inputs.'},{'name':'candidate.py','url':f'{BASE}/workflows/candidate.py','description':'Executable worked solutions; reads only the selected question input directory. Exclude from agent inputs.'},{'name':'verify.py','url':f'{BASE}/workflows/verify.py','description':'Evaluator-side numeric checker. Interpretation and figure readability require separate review.'}]
    workflow={'scenario_id':'GLEASON24-'+q,'question':title,'tool_environment':{'python':'3.10.20','numpy':'1.26.2','pandas':'1.5.3','scipy':'1.15.3','matplotlib':'3.10.9','pymatgen':'2024.3.1 (Q1 only)'},'input_boundary':'Only the scenario inputs and its background. No released output tables, verification files, local prior traces or live API calls.','steps':[{'step':i+1,'tool':tool,'operation':op,'artifact_or_check':artifact} for i,(tool,op,artifact) in enumerate(steps)],'candidate_command':f'python candidate.py {q} --inputs INPUT_DIRECTORY --output OUTPUT_DIRECTORY','verification_command':f'python verify.py {q} --output OUTPUT_DIRECTORY --truth verification/{q}','evidence':reason,'execution':{'status':'not_yet_executed'}}
    workflow_path=DOCS/BASE/'workflows'/f'{q}.json'
    if workflow_path.exists():
        previous=json.loads(workflow_path.read_text())
        workflow['execution']=previous.get('execution',workflow['execution'])
    workflow_path.write_text(json.dumps(workflow,ensure_ascii=False,indent=2)+'\n')
    verification={'description':check,'data':truth,'figures':figures or [],'methods':methods}
    if thresholds is not None:verification['thresholds']=thresholds
    return {'id':'GLEASON24-'+q,'kind':'Subquestion','title':title,'inputs':inputs,'prompt':{'background':background,'instruction':instruction},'verification':verification,'groundTruthReasoning':reason}

selection='Use the saved Materials Project Cu average, rounded to two decimals. The released workflow substitutes 0 when the Cu assignment is missing. Exclude material_id="Failed", records with an error or missing L3 reference, and labels ≥3. This is the historical data rule; an imputed zero is not independently established Cu(0).'
sc=[]
sc.append(make('Q1','What material-level Cu L₂,₃ spectrum is predicted for TbCu₅?',[
    file('Q1','L3_001_Cu_feff.inp','Unmodified FEFF input deck containing the six-atom unit cell; absorber indices in filenames are zero-based.'),
    *[file('Q1',f'{edge}_{site}_Cu_xmu.dat',f'Unmodified site-resolved FEFF {edge} output for Cu site {int(site)}. Column 1 is photon energy (eV) and column 4 is absorption.') for edge in ['L2','L3'] for site in ['001','002']]],
    'The supplied files contain separate Cu L₂ and L₃ FEFF spectra for the inequivalent Cu sites in TbCu₅ (Materials Project ID mp-1077262). The crystal structure is included in the FEFF input file. Use a positional symmetry tolerance of 0.01 Å when identifying equivalent Cu sites.',
    'Construct the material-averaged Cu L₂,₃ spectrum from the supplied simulations, preserving the FEFF energy and intensity conventions and resolving both edges. Determine the site weights from the structure. Save spectrum.csv with energy_eV,intensity, an overlay plot of weighted site contributions and their sum, and result.json containing material_id, site_weights keyed by zero-based site index, and points (your output row count). Justify how you combine the edges and handle interpolation, unequal energy ranges and site multiplicities.',
    'The six-atom TbCu5 cell contains five Cu atoms in multiplicity groups 1 and 4, so the weights are 0.2 and 0.8. The reference material spectrum is copied from the authors released pre-alignment table for mp-1077262. It has 545 samples, but that count is not a required answer. The candidate workflow retains the authors interpolation/padding recipe as one worked solution; other justified numerical treatments may pass. The optional saved L3 reference is an archival diagnostic, not part of this research question. This tests postprocessing of converged simulations, not a new FEFF calculation. Source: Database_Construction.ipynb cells 1, 7, 9 and 10.',
    'Require multiplicity-derived site weights and physically justified edge combination. Compare the reconstructed spectrum with the released material spectrum and inspect the contribution plot and reasoning. Different row counts, grids and padding functions are accepted. Numerical screening uses the separately documented benchmark thresholds below; other defensible methods need reviewer adjudication.',
    [('Python / pymatgen','Parse the structure header and identify symmetry-equivalent Cu sites using the supplied 0.01 Å tolerance.','Multiplicity-derived weights.'),('Python / NumPy','Worked replay choice: linearly interpolate each edge at 0.1 eV from round(min(E)+0.15,1) to round(max(E)−0.15,1), excluding the upper bound. Extend L₂ to the L₃ start with (E+a)^10 b through intensity 1e−10 there and the first L₂ sample. Sum edges on the L₃ grid, then average sites by multiplicity on their common interval, excluding its upper endpoint. These numerical choices are not required of the agent.','spectrum.csv; result.json; optional archival L3 energy reference.'),('Python / Matplotlib','Plot the two weighted site spectra and their sum.','plot.png'),('Evaluator / verify.py','Compare spectral shape and edge features on the reference interior range, check site weights, and review the physical justification.','Numerical screening plus scientific review, without an exact-array requirement.')],['spectrum.csv'],thresholds={
        'origin':'Benchmark-defined',
        'generatedBy':'Model-generated',
        'provenance':'These screening thresholds and comparison settings were generated by the model for this benchmark. They were not reported in the paper and are not physical uncertainty estimates. Scientific justification and plots require separate review.',
        'description':'Resample the candidate onto the reference interior range, excluding 0.5 eV at each reference boundary, without fitting an energy shift, amplitude scale or baseline. Require ≤2% RMSE normalized by the reference intensity range, edge-peak energy errors ≤0.2 eV, and relative peak-height and edge-area errors ≤5%. See comparison_policy.json for the edge windows and full comparison settings.',
        'data':[{'name':'comparison_policy.json','url':f'{BASE}/verification/Q1/comparison_policy.json','description':'Evaluator-only, model-generated benchmark thresholds and comparison settings; includes provenance.'}]
    }))
sc.append(make('Q2','How much of the base spectral set has an integer Cu oxidation-state label?',
    [file('Q2','material_records.json','Projection of pre-filter release records: IDs, saved oxidation-state dictionaries and L3 reference availability. Final labels, retained masks and counts are withheld.')],
    'These are computational assignments saved by the authors, not labels inferred from the spectra. '+selection,
    'Build the admissible base-material label distribution before synthetic augmentation. Save a count plot and result.json containing retained, integer_counts (keys "0","1","2"), fractional, integer_fraction, above_two_below_three, zero_from_missing, and zero_explicit. Count fractional labels without rounding them to the nearest integer. Explain what the zero-label provenance permits you to conclude chemically.',
    'The released processed table has 3,439 rows: 876, 1,039 and 1,291 with labels 0, 1 and 2, plus 233 fractional labels. The integer fraction is 3,206/3,439, approximately 93.2248%; 68 retained labels exceed 2. All 876 zero labels arise from missing Cu assignments in the saved dictionaries. This reproduces the released target distribution, not independent chemical validation. The targets are derived from the separate released processed table; input projections omit its answer columns. Figure 1 bar heights are not exact base-set truth because the author notebook plots after augmentation.',
    'Require exact counts and integer fraction within 1e−9. The interpretation must distinguish an imputed zero from an explicitly assigned Cu(0), and preserve original fractional labels. Compare against the released table, not the figure bar heights.',
    [('Python / JSON','Read the saved assignment dictionaries and reference-status records.','No live Materials Project access.'),('Python / NumPy','Apply the historical label and admissibility rules; count exact integer/fractional values and zero-label provenance.','result.json'),('Python / Matplotlib','Plot base-set label coverage.','plot.png'),('Evaluator / verify.py','Compare counts against the independent processed table reduction.','Numeric pass; reviewer checks provenance interpretation.')],[]))
sc.append(make('Q3','How do predicted stability and experimental structure evidence overlap in the retained materials?',
    [file('Q3','material_records.json','Pre-filter release metadata with oxidation dictionaries, reference status, is_stable and theoretical. Retained masks and category counts are withheld.')],
    'is_stable=True marks the saved predicted-stability category. theoretical=False marks a structure with experimental provenance; it does not mean its spectrum was measured experimentally. '+selection,
    'Determine the overlap of the two categories in the admissible base material set. Save a four-category plot and result.json with retained, stable, experimentally_known, both, stable_only, experimentally_known_only and neither. Explain whether adding the two inclusive category totals gives a valid material count.',
    'The released retained rows give 1,706 stable and 2,879 experimentally known, with 1,198 in both categories. Exclusive counts are 508 stable only, 1,681 experimentally known only, 1,198 both and 52 neither, totaling 3,439. Inclusive totals double-count the overlap. Figure 1 reports different snapshot counts; it supplies context, not the exact target for the later released table. The verification counts are independently reduced from the processed release flags.',
    'Require exact inclusive and exclusive counts and explain the overlap. Do not force the release counts to equal Figure 1. The four exclusive groups must sum to the retained total.',
    [('Python / JSON','Read the upstream metadata and apply the stated admissibility rule.','Retained material records.'),('Python / NumPy','Compute the two Boolean masks, their intersection and the four disjoint groups.','result.json'),('Python / Matplotlib','Plot the four exclusive categories.','plot.png'),('Evaluator / verify.py','Compare to the separately released retained table.','Exact counts and set-overlap interpretation.')],[],[figure('paper-figure-1.png','Figure 1 · provenance context','Author-provided Figure 1. Category counts differ from the released table and must not be used as exact numerical ground truth.')]))
sc.append(make('Q4','What cumulative model-input curves correspond to the Cu, Cu₂O and CuO reference spectra?',
    [file('Q4','reference_spectra.csv','Ordinary simulated spectra for mp-30, mp-361 and mp-704645, projected from the open release. Already aligned, baseline-shifted and normalized on 925–970 eV; cumulative columns are withheld.')],
    'The model representation uses cumulative spectral intensity normalized to its maximum. The released convention at sample k includes samples before k and excludes sample k. The uniform energy step is 0.1 eV; a constant integration factor cancels under normalization.',
    'Construct the three cumulative curves and save cumulative.csv with energy_eV,Cu,Cu2O,CuO, plus an overlay plot. Save result.json with materials in Cu/Cu2O/CuO order, points, first_value and last_value. Briefly describe where the ordinary absorption peaks produce rapid changes in the cumulative curves.',
    'The target cumulative arrays are copied directly from Cumulative_Spectra_TEAM_1_aligned_925_970 in the authors released table. They use sum(y[:k])/max_k(sum(y[:k])), so the first point is zero and the last is one across 451 samples. A standard inclusive cumsum or trapezoidal integral changes the representation and should not pass this convention-specific question. Source: Full_spectral_alignment.ipynb cell 60. This is a feature-construction question, not an independent oxidation-state prediction.',
    'Compare all three 451-point curves to released cumulative arrays at rtol=1e−7, atol=1e−8. Check the zero/one endpoints and the plot axes. Review the connection between peaks and steep cumulative changes; do not infer model accuracy from this transformation alone.',
    [('Python / pandas','Load the ordinary aligned spectra; check the common energy axis.','Three 451-point arrays.'),('Python / NumPy','Compute left-exclusive prefix sums and normalize each by its maximum.','cumulative.csv; result.json'),('Python / Matplotlib','Overlay the three cumulative representations.','plot.png'),('Evaluator / verify.py','Compare with cumulative arrays held back from the released table.','Array agreement and visual interpretation.')],['cumulative.csv']))
sc.append(make('Q5','What Cu L₂,₃ signal results from the paper’s displayed three-material spectral combination?',
    [file('Q5','parent_spectra.csv','Released ordinary spectra for HoCdCu4 (mp-12007), NdCuSi (mp-8120) and CuN2(Cl2O)2 (mp-1188453), already aligned and normalized. No mixture output is included.')],
    'The Figure 1 example combines these three parent signals linearly using display coefficients 0.33, 0.33 and 0.33. Use those coefficients exactly: this plotting call does not rescale them to sum to one. This task concerns the displayed signal; the training-data generator has a separate normalization rule.',
    'Compute the three weighted contributions and total signal on the shared energy grid. Save mixture.csv with energy_eV,weighted_0,weighted_1,weighted_2,mixture, and plot dashed components with their summed curve. Save result.json with parent_ids, coefficients, coefficient_sum and points. Explain why the summed curve can exceed each individual weighted contribution.',
    'The authors plotting call in Paper_Figures.ipynb cell 16 uses these IDs and coefficients directly. Their sum is 0.99. The evaluator table is a deterministic weighted sum recomputed from the released parent arrays; it is not a separately released mixture table. The independently embedded author plot supplies a shape check. The parents are not the Cu/Cu2O/CuO standards. The total is pointwise additive, explaining why it can exceed each weighted component.',
    'Require the weighted components and total at rtol=1e−7, atol=1e−8, including the 0.99 coefficient sum. Compare curve order, peak locations and relative heights to the embedded author plot; styling need not match. Require an additive-signal interpretation, without claiming measured mass fractions.',
    [('Python / pandas','Load the three parent curves and shared energy axis.','Parent spectra only.'),('Python / NumPy','Multiply each parent by 0.33 and sum pointwise without a second normalization.','mixture.csv; result.json'),('Python / Matplotlib','Overlay dashed contributions and the red sum.','plot.png'),('Evaluator / numerical and image comparison','Check weighted sums and compare to the author notebook figure.','Algebraic numerical check plus independent plot evidence.')],['mixture.csv'],[figure('notebook-ternary-mixture.png','Author notebook · displayed ternary mixture','Unmodified embedded plot from Paper_Figures.ipynb cell 16, output 2. Supports the curve shapes; numeric reference is a recomputation.')]))
sc.append(make('Q6','How does synthetic mixture augmentation change Cu oxidation-state coverage?',
    [file('Q6','ordered_base_labels.csv','Only the released base material IDs and oxidation labels, in original row order. No synthetic rows or augmented counts. Spectral arrays are unnecessary for this label-coverage question.')],
    'Generate the paper’s three mixture families: all (0/1/2), 0-1 and 1-2. For each family reset NumPy RandomState(32). For each of 100 draws, select one parent from each exact-label pool in order 0,1,2 using randint, retaining input order within pools. Then draw 20 label-0 raw coefficients from linspace(1,0,101) unless family 1-2; draw 20 label-2 coefficients from linspace(0,1,101) unless family 0-1; finally draw 20 label-1 coefficients from linspace(0,1,101). Inactive coefficients are zero without an RNG call. Normalize each coefficient triple, skip all-zero triples, and round the weighted label to two decimals using NumPy scalar rounding. Retain original fractional-label materials but do not draw parents from them.',
    'Determine the label coverage after appending the generated mixtures to the base set. Save manifest.csv with type,id_0,id_1,id_2,weight_0,weight_1,weight_2,label. In result.json report base_rows, generated_by_family, generated, augmented, synthetic_integer_labels, augmented_integer_counts, histogram_counts, histogram_edges, histogram_total and fractional_outside_histogram. The histogram uses 20 equal bins from 0 through 2 and excludes labels exactly 0,1,2, which are separate bars. Plot the resulting coverage and explain any difference from the nominal number of requested mixtures.',
    'Replay of the unchanged author generation methods on the released base table produces 5,999 mixtures: 2,000 all, 2,000 0-1 and 1,999 1-2. One zero-sum draw is skipped. The augmented size is 9,438. Synthetic integer labels contribute 127 rows; final integer bars are 906, 1,108 and 1,319. The noninteger histogram contains 6,037 entries, while 68 original fractional labels lie above its range. This is a code-replay target, not an independently archived historical mixture table. Source: Paper_Figures.ipynb cell 4 and Analysis_objects_and_functions.py methods augment_df_with_mixtures/add_mixed_valent_spectra.',
    'Require exact counts, histogram bins and the parent-ID ordering in the manifest; weights/labels use rtol=1e−7, atol=1e−8. Compare qualitatively with the author distribution plot, acknowledging the released-base snapshot may differ. Require an explanation of skipped all-zero draws and rounded integer mixtures. This question does not test model training or synthetic spectral shapes.',
    [('Python / pandas','Load ordered IDs and labels and form exact 0/1/2 parent pools.','Ordered parent pools.'),('Python / NumPy RandomState','Generate parent selections and coefficients using the stated family-specific draw order.','manifest.csv'),('Python / NumPy','Append synthetic labels; compute exact-integer bars and fractional histogram.','result.json'),('Python / Matplotlib','Plot the augmented label coverage.','plot.png'),('Evaluator / verify.py','Compare with prior unchanged-author-code replay and inspect the coverage explanation.','Replay agreement, not independent historical ground truth.')],['manifest.csv'],[figure('notebook-augmented-distribution.png','Author notebook · augmented label distribution','Unmodified embedded plot from Paper_Figures.ipynb cell 13. Use for qualitative shape/context, not exact snapshot counts.')]))
sc.append(make('Q7','How separated are the experimental Cu, Cu₂O and CuO L₃ peak energies?',
    [file('Q7',name+' XAS.csv','Unmodified literature XAS CSV from the open release: energy in eV and intensity. These are released digitized spectra, not detector-raw measurements.') for name in ['Cu Metal','Cu2O','CuO']],
    'Compare the spectra on their supplied energy axes without an additional energy shift or smoothing. For this question define the L₃ peak as the largest tabulated intensity between 930 and 940 eV inclusive. Sorting is permitted for plotting; plot amplitudes may be normalized independently without changing peak positions. Fine oscillations in these digitized traces are not a target for physical interpretation.',
    'Locate the three L₃ peak energies and compare their separations. Save result.json with L3_peak_eV (keys "Cu Metal","Cu2O","CuO"), Cu2O_minus_Cu_eV, CuO_minus_Cu_eV and CuO_minus_Cu2O_eV. Make an overlay marking the peak positions. Explain whether peak energy alone is likely to separate all three oxidation-state references.',
    'The supplied XAS maxima occur at 933.65 eV (Cu), 933.6691148 eV (Cu2O) and 931.2967241 eV (CuO). The first pair differs by approximately 0.0191 eV, whereas CuO is about 2.35–2.37 eV lower. These exact values are independently reduced from the supplied CSVs; the paper does not publish this exact peak table. Figure S1 supports the qualitative near-coincidence of Cu/Cu2O and lower-energy CuO feature after smoothing and author shifts of −1.0/−1.2/−1.2 eV. Its plotted absolute peak energies are not the unshifted CSV targets. The comparison supports a limitation of peak-position-only discrimination, not a claim that the complete spectra are indistinguishable.',
    'Allow 0.05 eV absolute error on peak positions and signed separations. Check that Cu/Cu2O are nearly coincident and CuO is lower in energy; compare the marked overlay with Figure S1 XAS traces. The candidate must limit its conclusion to peak energy and these supplied references.',
    [('Python / pandas','Read the three unchanged XAS CSVs; retain their supplied energy calibration.','Input data frames.'),('Python / NumPy','Find each maximum within the defined window and calculate signed pairwise energy differences.','result.json'),('Python / Matplotlib','Sort for display, normalize amplitudes and overlay the L₃ peaks.','plot.png'),('Evaluator / numeric and figure review','Compare peak positions to an independent CSV reduction and inspect Figure S1 consistency.','Numerical peaks plus appropriately limited scientific inference.')],[],[figure('paper-figure-s1.png','Figure S1 · reference spectra','Author-provided Figure S1. Its literature XAS traces were smoothed and shifted by −1.0 eV (Cu) and −1.2 eV (Cu2O/CuO). Use qualitative peak ordering only; exact targets use the supplied unshifted CSVs.')]))

paper={'id':'gleason-2024-cu-oxidation','title':'Prediction of the Cu oxidation state from EELS and XAS spectra using supervised machine learning','authors':'Samuel P. Gleason, Deyu Lu and Jim Ciston (2024)','doi':'10.1038/s41524-024-01408-1','category':'Cu oxidation-state spectroscopy','facility':'Materials Project / FEFF9; NCEM Molecular Foundry; CFN Brookhaven','pdf':PAPER+'.pdf','dataUrl':'https://zenodo.org/records/18142209','codeUrl':CODE,'scenarios':sc}
path=DOCS/'data/benchmark.json';data=json.loads(path.read_text());data['papers']=[p for p in data['papers'] if p['id']!=paper['id']]+[paper]
# Q1 now tests scientific reconstruction rather than exact numerical replay.
data['datasetId']='spectral-agent-v3';path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
(ROOT/'papers/gleason-2024-cu-oxidation/paper.json').write_text(json.dumps(paper,ensure_ascii=False,indent=2)+'\n')
print('Added',len(sc),'independent questions to',path)
