#!/usr/bin/env python3
"""Register this paper, preserving all other benchmark entries."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];PAPER=Path(__file__).resolve().parent;BASE=ROOT/'docs/data/szymanski-2024-xrd-pdf';URL='data/szymanski-2024-xrd-pdf'
def write(p,v):p.write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
def link(name,path,description):return dict(name=name,url=f'{URL}/{path}',description=description)
protocol={
 'purpose':'A fixed, inexpensive baseline experiment on released spectra. These settings define comparable controlled experiments; they are not an optimized phase-identification system.',
 'common':{'angle_grid':{'min_deg':10.02,'max_deg':79.98,'points':2001,'interpolation':'linear on native two-theta; no extrapolation'},'intensity':'Subtract each resampled spectrum\'s 10th percentile and divide by its resulting positive maximum; retain negative values. No rolling-ball correction, clipping, or smoothing.','virtual_pdf':'Q = 4*pi*sin(two_theta*pi/360)/1.5406 (angstrom^-1). G(r)=(2/pi)*integral Q*I(Q)*sin(Q*r)dQ, trapezoid on the nonuniform Q grid. This is an uncorrected virtual PDF, not a quantitative pair density.','r_grid':{'min_angstrom':1,'max_angstrom':40,'points':1000},'model_features':'Normalize each XRD or virtual-PDF vector to unit L2 norm independently before classification or fitting.'},
 'Q1':{'split':'Within each phase identity, sort native replicate index ascending; first floor(0.7*n) are training, remainder testing. Metadata records this deterministic split.','estimator':'Separate RidgeClassifier(alpha=1, solver=cholesky) models for XRD and PDF; default intercept, no class balancing. Apply softmax across each decision vector to obtain relative scores; average the two score vectors for Fused. These scores are not calibrated probabilities.','inference':'Highest score, alphabetical phase-ID tie-break. Test labels are used only after predictions.','report':'Micro-F1 (equal to accuracy for one label), exact match, paired error-complementarity counts, and chemistry-specific results.'},
 'Q2':{'reference_library':'For each phase identity, average individually preprocessed training spectra using the Q1 split; compute its PDF after averaging. No mixture spectra or labels enter template construction.','fit':'For each representation, use unit-L2 templates and targets. Minimize ||D*c-y||^2 + 1e-10*||c||^2 subject to c>=0. Divide coefficients by their sum. Fused scores are the arithmetic mean of the two normalized coefficient vectors.','inference':'The supplied 2-Phase or 3-Phase group provides the true cardinality K. Select top K scores, ties by alphabetical ID. Coefficients are spectral scales, not mass fractions.','report':'Micro-F1, exact phase-set accuracy and paired error complementarity separately by chemistry and phase count. No mixtures are used for training/tuning.'},
 'Q3':{'baselines':'All released Li2TiO3_15 single-phase records; use individually preprocessed XRD as baselines (already augmented in the release).','added_noise':'Independent Gaussian values at each of 2001 angle points, standard deviation 0.01 and 0.03 of the preprocessed peak height. Five trials per baseline. numpy.random.default_rng seed=202409+100*i+trial where i is zero-based position in the full Li-Ti-P-O_1-Phase.json array. Same draw rescaled across the two amplitudes.','added_background':'A*exp(-0.5*((two_theta-35)/12)^2), A=0.05 and0.20. One deterministic trial per amplitude.','transform':'Add perturbations to preprocessed baseline without further subtraction or renormalization, then apply common transform over r=linspace(1,120,1191).','windows':{'1-5':'1 <= r < 5','5-40':'5 <= r < 40','1-40':'1 <= r < 40','40-120':'40 <= r <=120'},'metrics':'Per baseline/trial/window: ||delta_XRD||/||baseline_XRD||; ||delta_G_window||/||G_window||; sum(G_window^2)/sum(G_1to120^2); sum(delta_G_window^2)/sum(delta_G_1to120^2). Use sampled sums. Report arithmetic means by artifact/amplitude/window and full per-trial results. Energy retention is not proof of classification information retention.'},
 'Q4':{'library':'Use the Q1 training subset and Q2 template fitting. Candidate formulas: Li-La-Zr-O: La(OH)3, Li2CO3, LiOH, ZrO2. Li-Ti-P-O: Li2CO3, Li2TiO3, Li3PO4, TiO2. Include every available polymorph within these known reagent lists.','inference':'Fit individual phase-ID templates; normalize nonnegative coefficients across phase IDs, then sum scores over polymorphs of each formula. Average XRD/PDF formula scores for Fused. Select top two formulas. Neither the known phase identities nor abundance labels of a target may enter fitting.','report':'Micro-F1, exact pair accuracy, secondary-phase recall and paired error-complementarity counts by chemistry and known secondary wt%. Do not equate fitted intensity coefficients with weight fractions or infer a universal limit of detection.'},
 'evaluation_boundary':'Labels and split metadata are scientific evaluation data. They must not be supplied to feature construction or prediction for a target. Keep inference traces and evaluate afterward. An output-only grader cannot prove this separation.'}
write(BASE/'inputs/protocol.json',protocol)
write(BASE/'inputs/output_schema.json',{'all':['result.json','diagnostics.png','conclusion.md','probe.npz'], 'classification':{'questions':['Q1','Q2','Q4'],'predictions.csv':'Exactly one row for every evaluated id and each model XRD,PDF,Fused. Columns id,chemistry,model,predicted (JSON list),scores (JSON object from label to finite score). All candidate labels must occur in scores.','split_trace.json':'Complete single-phase reference train/test partition per chemistry. For Q2/Q4, test IDs here are unused reference holdouts; evaluated mixture IDs are in predictions.csv.','result.json':{'question':'Q1, Q2, or Q4','summaries':'Records chemistry,group,model,n,micro_f1,exact_match. Q4 also minor_recall. group=single for Q1, 2-Phase or3-Phase for Q2, secondary wt% string for Q4.','complementarity':'Records chemistry,group,n,xrd_only_correct,pdf_only_correct,both_correct,neither_correct; correctness means exact label set.'}},'Q3':{'metrics.csv':'id,artifact,amplitude,trial,window,xrd_relative_l2,pdf_relative_l2,signal_energy_fraction,artifact_energy_fraction','curves.npz':'r vector; baseline curves named {id}_base; perturbed curves {id}_{artifact}_{amplitude}_{trial}. Amplitude uses Python float string (.01→0.01).','result.json':'question=Q3; source_patterns; summaries with artifact,amplitude,window,n and means of the four metrics.'},'probe.npz':'One-dimensional theta,r,xrd,pdf arrays plus string probe_id, with unnormalized G computed from preprocessed peak-normalized XRD. First evaluated record for classification; first Li2TiO3 baseline for Q3.','conclusion':'State the evidence-backed answer, numerical effect sizes and scope limits; figures should show the asked comparisons.'})
(BASE/'inputs/README.md').write_text('''# Input field definitions

Numeric spectra are the earliest released measurements/simulations, not detector frames. Files are lossless float64 projections of the public numeric text files. Simulation NPZ files contain a shared `theta` array in degrees and a one-dimensional intensity array under each anonymous sample ID. Experimental NPZ files contain a native two-column `(two_theta_degrees, intensity)` array per ID. Load with `numpy.load(..., allow_pickle=False)`.

Each matching JSON file is an ordered metadata array. `phases` contains formula plus space-group suffix for simulated data, and formula only for experiments. `replicate` is the native simulation index; `split` defines training/testing for singles. Experimental `major`, `minor`, and `minor_weight_percent` describe prepared mixtures. These are evaluation labels: do not use target labels as prediction features. `kind` gives known phase cardinality. Arrays retain negative simulated noise values. Experimental intensities are arbitrary counts; simulated intensities are relative units.

The numerical protocol freezes representation and baseline models for a paired scientific comparison. It supplies neither fitted parameters nor expected outcomes. Each question stands alone. Its protocol section, common settings, and explicitly referenced section definitions apply; no result from another question is needed. The output schema defines files for evaluator comparison. The original phase-bearing filenames, source hashes, historical context and worked answers remain evaluator-side.

Source: Nathan Szymanski (2023), Integrated analysis of XRD patterns and PDFs, figshare version 1, DOI 10.6084/m9.figshare.24043410.v1, CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/). Packaging renames files and separates labels; no numerical filtering or processing is performed. The native scan grids differ; inspect rather than assume their endpoints.
''')
questions=[
 ('Q1','Which representation gives more reliable phase identification on held-out simulated patterns?',
  'The supplied powder diffraction simulations cover two chemical spaces and contain repeated augmented patterns of known crystalline phases. Each phase identity includes a formula and a space-group identifier. A virtual PDF is an alternative representation obtained by a sine transform of the diffraction intensities.',
  'Compare phase identification from XRD and virtual-PDF representations using the paired training/test protocol. Determine whether averaging their scores improves identification and whether their errors occur on the same samples. Report chemistry-specific held-out performance, paired error counts, diagnostic plots and a concise interpretation of what this split establishes.',
  ['1-Phase'],'Fresh supervised models; separate representations and paired errors.',
  'Single-phase identification and complementary representation errors; related to Results: Influence of the number of phases present and Fig.2. Ridge models and the fixed split are benchmark choices, not historical CNN reconstructions.'),
 ('Q2','How does increasing phase count affect recovery of constituent identities from XRD and virtual-PDF template fits?',
  'The inputs include single-phase reference simulations and simulated mixtures containing either two or three crystalline phases. The number of constituents is supplied, while their identities must be inferred from the spectra. Spectral contribution coefficients need not equal mass fractions.',
  'Build references from the prescribed single-phase training subset and compare nonnegative template recovery in XRD and virtual-PDF space as the number of phases increases. Evaluate both individual representations and averaged scores, including exact phase-set recovery, micro-F1 and complementary errors. Explain what the results support about overlapping phases and what supplying the phase count leaves untested.',
  ['1-Phase','2-Phase','3-Phase'],'Reference construction and constrained spectral decomposition.',
  'Multiphase recovery from Fig.2 and the discussion of overlapping PDF features. Nonnegative mean-template fitting with supplied cardinality is a controlled baseline and does not reproduce iterative CNN/subtraction.'),
 ('Q3','How do additive noise and smooth background alter virtual PDFs across distance windows?',
  'The supplied single-phase simulations include several realizations of Li2TiO3. Their existing artifacts remain part of the baseline. Controlled added perturbations can reveal how representation and distance-window choices change sensitivity.',
  'Using the specified repeated noise and smooth-background perturbations, determine how distortion varies across distance windows and how much baseline signal each window retains. Produce per-trial measurements, aggregated comparisons and diagnostic plots, then recommend a window for these perturbations with a quantified tradeoff. Distinguish retained signal energy from evidence of retained phase-identification accuracy.',
  ['1-Phase'],'Paired perturbation experiment and window-selection tradeoff.',
  'Artifact localization and r-window design related to Fig.5 and the Methods/Discussion. These perturbations are generated during solving from raw released baselines; they are not the missing categorized historical artifact dataset.'),
 ('Q4','How well do simulation-derived references recover secondary phases in measured binary mixtures as abundance decreases?',
  'The measured powder diffraction patterns are binary mixtures in two chemical spaces. Each chemistry has four candidate reagent formulas, potentially represented by several simulated polymorphs. Preparation labels identify the secondary formula and its known weight percentage for evaluation.',
  'Use simulation-derived references to identify both formulas in every measured mixture without using its preparation labels during fitting. Compare XRD, virtual-PDF and averaged-score predictions across secondary-phase abundance. Report formula-level micro-F1, exact-pair accuracy and secondary-phase recall by chemistry and abundance, and explain whether a consistent detection trend is supported. State the limits of interpreting template coefficients and drawing detection-limit conclusions.',
  ['1-Phase','Experiments'],'Transfer from simulations to experiments and minority detection.',
  'Experimental validation and secondary-abundance dependence related to Fig.6. Known four-formula libraries and nonnegative fits differ from the paper CNNs. Formula-level scoring cannot resolve polymorph correctness.')]
scenarios=[]
for q,title,bg,instruction,kinds,analysis,source in questions:
 inputs=[]
 for chem in (['Li-Ti-P-O'] if q=='Q3' else ['Li-La-Zr-O','Li-Ti-P-O']):
  for kind in kinds:
   stem=chem+'_'+kind
   inputs += [link(stem+'.npz','inputs/'+stem+'.npz','Native-angle numeric spectra with anonymous record IDs; no resampling or derived features.'),link(stem+'.json','inputs/'+stem+'.json','Record identities, raw labels and evaluation metadata; target labels excluded during inference.')]
 for f,desc in [('protocol.json','Fixed paired comparison design and numerical conventions, with no fitted outputs.'),('output_schema.json','Required numerical outputs and trace format.'),('README.md','Input array definitions, units and label semantics.')]:inputs.append(link(f,'inputs/'+f,desc))
 base_reason=f'''1. Use Python/NumPy to read only the linked raw numeric NPZ arrays and metadata. Interpolate onto the shared angular interval, subtract the declared intensity percentile and scale by peak height. The source audit verifies every packaged array against the release.\n\n2. Use NumPy to compute the uncorrected sine-transform representation with nonuniform-Q trapezoidal quadrature. The independent verifier recomputes a raw-linked transform probe without importing the candidate.\n\n'''
 op={'Q1':'Fit separate scikit-learn RidgeClassifier models on unit-length XRD and virtual-PDF features from training IDs. Predict withheld repeats, convert decision vectors to relative scores and average across representations. Use Python set/count operations to calculate phase accuracy and paired exact-correctness categories.', 'Q2':'Average only training spectra by phase identity. Use SciPy nonnegative least squares (with the declared tiny L2 penalty) to fit unit-normalized templates to mixture spectra in each representation. Normalize coefficients and average scores. Select the supplied number of constituents, then compute identity-recovery metrics separately for two- and three-phase mixtures.', 'Q3':'Select all 11 released Li2TiO3_15 realizations. Use NumPy PCG64 draws for five repeated noise perturbations at each of two amplitudes and construct two smooth Gaussian backgrounds. Transform baseline and perturbed traces through r=120 Å. Compute per-window relative distortions and sampled signal/artifact energy fractions, then aggregate over trials and baselines.', 'Q4':'Restrict single-phase references to the four candidate formulas per chemistry, retaining their polymorphs. Use the same nonnegative template fit as the simulation benchmark; sum coefficient scores by formula, average representations and select two formulas. Only afterward use preparation labels to evaluate secondary recall, exact pair recovery and micro-F1 at each abundance.'}[q]
 resultfile=BASE/'verification'/q/'result.json'
 finding='Reference execution is recorded in the linked evaluator files.'
 if resultfile.exists():
  result=json.loads(resultfile.read_text())
  if q in ['Q1','Q2']:
   finding='Executed results: '+'; '.join(f"{s['chemistry']} {s['group']} {s['model']} F1 {s['micro_f1']:.4f}, exact {s['exact_match']:.4f}" for s in result['summaries'])+'.'
  elif q=='Q3':
   ss=[s for s in result['summaries'] if s['window']=='5-40' and s['amplitude'] in [.03,.2]];finding='Executed 5–40 Å tradeoff: '+'; '.join(f"{s['artifact']}, amplitude {s['amplitude']}: mean PDF distortion {s['pdf_relative_l2']:.5f}, retained baseline energy {s['signal_energy_fraction']:.4f}" for s in ss)+'.'
  else:
   ss=[s for s in result['summaries'] if s['group'] in ['2','20']];finding='Endpoint results: '+'; '.join(f"{s['chemistry']} {s['group']} wt% {s['model']} secondary recall {s['minor_recall']:.3f}" for s in ss)+'.'
 reasoning=base_reason+'3. '+op+'\n\n4. Use Matplotlib to save diagnostics.png and write an evidence-backed conclusion alongside the numerical outputs. '+finding+'\n\n5. Evaluator only: run the independently implemented verifier against the original-filename label map, numerical reference and raw-linked transform check. Apply deliberately corrupted-output controls and inspect the scientific conclusion and plots. The separate execution agent reruns every question from packaged inputs in a clean output directory.\n\nSource relationship: '+source
 evidence=[link('result.json',f'verification/{q}/result.json','Executed modern baseline targets; not historical model scores.'),link('source_labels.json','verification/source_labels.json','Evaluator-only original-filename/source-hash mapping anchoring labels.'),link('provenance.json','provenance.json','Archive checksum, inventory, raw-value packaging and availability limits.')]
 for f in ['workflow_execution_review.json','verification_audit.json','question_quality_review.json','input_projection_audit.json']:
  if (BASE/'verification'/f).exists():evidence.append(link(f,'verification/'+f,'Independent review/execution evidence.'))
 for f in (['metrics.csv','curves.npz'] if q=='Q3' else ['predictions.csv']):evidence.append(link(f,f'verification/{q}/'+f,'Held-back numerical reference output for this fixed protocol.'))
 scenarios.append(dict(id='SZYMANSKI24-'+q,kind='Subquestion',executionStatus='validated',title=title,inputs=inputs,prompt=dict(background=bg,instruction=instruction+' Use protocol.json and output_schema.json for the controlled comparison and output contract.'),groundTruthReasoning=reasoning,verification={'description':'Recompute metrics against original source labels (or independently regenerated perturbations for Q3), validate row coverage, train/test separation, normalized scores, fusion and raw-linked sine transform. Compare with the executed deterministic baseline reference. Require an evidence-backed scientific conclusion and diagnostic plots. Passing numerical checks alone cannot establish absence of label leakage; use an isolated input bundle and retain execution traces.','data':evidence,'figures':[{'image':f'{URL}/verification/{q}/diagnostics.png','label':q+' executed baseline diagnostics','caption':'Benchmark-generated comparison, not a paper figure. '+source}], 'methods':[link('candidate.py','workflows/candidate.py','Executed worked solution using only the raw input bundle.'),link('conclusion.md',f'verification/{q}/conclusion.md','Executed evidence-backed scientific interpretation and scope limits.'),link('verify.py','workflows/verify.py','Independent numerical checker; evaluator-side only.'),link(q+'.json','workflows/'+q+'.json','Tool calls, command, outputs and source relationship.')], 'thresholds':{'origin':'Benchmark-defined numerical reproducibility tolerances','generatedBy':'Independent verification agent; reviewed against deterministic double-precision outputs.','provenance':'These are software agreement tolerances, not measurement error bars or paper-reported thresholds. Original filename labels are exact anchors; model targets are newly computed controlled baselines.','notes':[{'title':'Numerics','description':'Exact sample/label coverage and counts; per-score and metric agreement follows verify.py (relative 1e-6 and absolute 1e-7 for model scores; absolute 1e-10 for classification metrics; Q3 metric agreement within 1e-9; transforms within relative/absolute 1e-9). Scientific interpretation and equivalent-method answers require evaluator review.'}]}}))
 workflow={'question':q,'runtime':'Use the Python interpreter from the pinned environment created in the entry README; run from the spectral_agent_bench root.', 'tools':['Python 3.12','NumPy','SciPy','scikit-learn' if q!='Q3' else 'NumPy random.Generator','Matplotlib'],'analysis':analysis,'command':f'OPENBLAS_NUM_THREADS=1 MPLCONFIGDIR=/tmp/szymanski-mpl /tmp/xrd-bench-env/bin/python docs/{URL}/workflows/candidate.py {q} --inputs docs/{URL}/inputs --output /tmp/szymanski-answer/{q}','verification_command':f'/tmp/xrd-bench-env/bin/python docs/{URL}/workflows/verify.py --question {q} --output /tmp/szymanski-answer/{q}','source_relationship':source,'steps':[base_reason,op,'Write predictions/metrics, result.json, probe.npz, diagnostics.png and conclusion.md.','Evaluator independently checks outputs against source labels, transform calculation and executed references.'],'input_boundary':'Candidate has no need to read paper, released models, original answer-bearing paths, reference outputs or other question outputs.'}
 write(BASE/'workflows'/f'{q}.json',workflow)
paper=dict(id='szymanski-2024-xrd-pdf',title='Integrated analysis of X-ray diffraction patterns and pair distribution functions for machine-learned phase identification',authors='Nathan J. Szymanski, Sean Fu, Ellen Persson and Gerbrand Ceder (2024)',doi='10.1038/s41524-024-01230-9',category='Powder XRD and virtual pair distribution functions',facility='Simulated powder diffraction / laboratory Cu Kα XRD',pdf='https://www.nature.com/articles/s41524-024-01230-9.pdf',dataUrl='https://doi.org/10.6084/m9.figshare.24043410.v1',codeUrl='https://github.com/njszym/XRD-AutoAnalyzer/tree/bf32082521e45c0fcf5cf9ae9bd1321e76bf9012',scenarios=scenarios)
write(PAPER/'paper.json',paper)
p=ROOT/'docs/data/benchmark.json';dataset=json.loads(p.read_text());dataset['papers']=[x for x in dataset['papers'] if x['id']!=paper['id']]+[paper];dataset['datasetId']='spectral-agent-v1-20260925-szymanski';write(p,dataset)

# Refresh package hashes after writing protocol/schema; source members are unchanged.
p=BASE/'provenance.json'
if p.exists():
 provenance=json.loads(p.read_text());provenance['input_files']={f.name:__import__('hashlib').sha256(f.read_bytes()).hexdigest() for f in sorted((BASE/'inputs').iterdir()) if f.is_file()};write(p,provenance)
